[package]
name = "rocket-add"
version = "0.1.0"
authors = ["c-ameron <pnzreba@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
math_utils = { version = "0.1.0", git = "ssh://git@github.com/c-ameron/rust-math-utils.git"}
